# Generated by Django 5.0.6 on 2024-05-14 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_category_remove_menuitem_tags_for_table_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='img',
            field=models.ImageField(default='null', upload_to='images/categories/'),
            preserve_default=False,
        ),
    ]
