# Generated by Django 5.0.6 on 2024-05-16 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_category_options_category_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='big_img',
            field=models.ImageField(default='', upload_to='images/menu/'),
            preserve_default=False,
        ),
    ]
